"""
scons build file

	p

@author: Jean-Lou Dupont
"""

Import('env')

d = env.Dictionary()

#no difference at this point
if d.get('_DEBUG', False):
	#DEBUG
	libs=['ei',]
	pr = env.SharedLibrary('epapi_debug', Glob("src/*.cc"), LIBS=libs )	
	env.Install('/usr/lib', '#lib/debug/libepapi_debug.so')
else:
	#RELEASE
	libs=['ei',]
	pr = env.SharedLibrary('epapi', Glob("src/*.cc"), LIBS=libs )
	env.Install('/usr/lib', '#lib/release/libepapi.so')
	
Default(pr)
	
env.Alias('install', '/usr/lib')

env.Install('/usr/include', '#lib/include/epapi.h')
env.Alias('installh', '/usr/include')
