EPAPI: MsgHandler Class Reference
MsgHandler Class Reference
#include <epapi_msg.h>
Public Member Functions
MsgHandler (PktHandler *ph)
~MsgHandler ()
void registerType (msg_type type, msg_type_text ttype, const char *signature)
int send (msg_type type,...)
int rx (Msg **m)
Static Public Attributes
static const int MAX_TYPE_LENGTH = 32
static const int MAX_ATOM_SIZE = 32
static const int MAX_STRING_SIZE = 4000
Protected Member Functions
const char * getSignature (msg_type type)
const char * getSignatureFromTypeText (msg_type_text ttype)
const char * getTextFromType (msg_type type)
Protected Attributes
PktHandler * ph
TypeMap tmap
TypeTextMap ttmap
Detailed Description
Message Handler
This class serves as the main API for clients.
Definition at line 123 of file epapi_msg.h.
Constructor & Destructor Documentation
MsgHandler::MsgHandler (PktHandler * ph)
Constructor
Parameters:
ph PktHandler instance
Definition at line 158 of file epapi_msg.cc.
References epapiBase::last_error, and ph.
MsgHandler::~MsgHandler ()
Destructor
Definition at line 163 of file epapi_msg.cc.
References ph.
Member Function Documentation
void MsgHandler::registerType (msg_type type, msg_type_text ttype, const char * signature)
Registers a message type
The parameter ttype corresponds to the ATOM element in string format.
Parameters:
type msg_type (an integer identifier)
ttype text string corresponding to msg_type
signature (combination of [A|L|S|D])
Definition at line 170 of file epapi_msg.cc.
References tmap, and ttmap.
int MsgHandler::send (msg_type type, ...)
Generic send message
Parameters:
msg_type message type (integer)
Returns:
0 SUCCESS
1 FAILURE
Builds a 'packet' according to the specified type. The type must have been previously registered.
Parameters:
type message type
Returns:
0 SUCCESS
1 FAILURE
Definition at line 241 of file epapi_msg.cc.
References DBGLOG, EEPAPI_BADFORMAT, EEPAPI_BADTYPE, EEPAPI_EIENCODE, EEPAPI_MALLOC, EEPAPI_NEWEIBUF, getSignature(), getTextFromType(), Pkt::getTxBuf(), epapiBase::last_error, ph, and PktHandler::tx().
int MsgHandler::rx (Msg ** m)
Generic receive message
Parameters:
**m Pointer to receive a Msg instance
Returns:
0 SUCCESS
1 FAILURE
Message Receive (blocking)
Parameters:
m pointer to message
Returns:
0 SUCCESS
1 FAILURE
Definition at line 378 of file epapi_msg.cc.
References DBGLOG, EEPAPI_ARITY, EEPAPI_BADFORMAT, EEPAPI_EIDECODE, EEPAPI_MALLOC, EEPAPI_TOOBIG, Pkt::getBuf(), getSignatureFromTypeText(), epapiBase::last_error, MAX_ATOM_SIZE, Msg::MAX_PARAMS, MAX_STRING_SIZE, MAX_TYPE_LENGTH, ph, and PktHandler::rx().
const char * MsgHandler::getSignature (msg_type type) [protected]
Returns the signature corresponding to a type.
Used during message transmission/encoding.
Parameters:
type msg_type (integer)
Returns:
signature signature or NULL for not found
Definition at line 180 of file epapi_msg.cc.
References EEPAPI_NOTFOUND, epapiBase::last_error, and tmap.
Referenced by getSignatureFromTypeText(), and send().
const char * MsgHandler::getSignatureFromTypeText (msg_type_text ttype) [protected]
Returns the signature corresponding to a type text.
Used during message reception/decoding.
Parameters:
ttype msg_type_text
Returns:
signature NULL on FAILURE
Definition at line 195 of file epapi_msg.cc.
References EEPAPI_NOTFOUND, getSignature(), epapiBase::last_error, and ttmap.
Referenced by rx().
const char * MsgHandler::getTextFromType (msg_type type) [protected]
Returns the ATOM text from a msg_type
Parameters:
type msg_type (integer)
Returns:
string representing the ATOM corresponding to message type
Definition at line 216 of file epapi_msg.cc.
References EEPAPI_NOTFOUND, epapiBase::last_error, and ttmap.
Referenced by send().
Field Documentation
const int MsgHandler::MAX_TYPE_LENGTH = 32 [static]
Maximum length the 'message type' field can be.
Definition at line 130 of file epapi_msg.h.
Referenced by rx().
const int MsgHandler::MAX_ATOM_SIZE = 32 [static]
Maximum size for an ATOM element
Definition at line 135 of file epapi_msg.h.
Referenced by rx().
const int MsgHandler::MAX_STRING_SIZE = 4000 [static]
Maximum size for a STRING element
Definition at line 140 of file epapi_msg.h.
Referenced by rx().
PktHandler* MsgHandler::ph [protected]
Definition at line 144 of file epapi_msg.h.
Referenced by MsgHandler(), rx(), send(), and ~MsgHandler().
TypeMap MsgHandler::tmap [protected]
Definition at line 145 of file epapi_msg.h.
Referenced by getSignature(), and registerType().
TypeTextMap MsgHandler::ttmap [protected]
Definition at line 146 of file epapi_msg.h.
Referenced by getSignatureFromTypeText(), getTextFromType(), and registerType().
The documentation for this class was generated from the following files:
lib/include/epapi_msg.h
lib/src/epapi_msg.cc