EPAPI: PktHandler Class Reference
PktHandler Class Reference
Packet Handler class declaration.
#include <epapi_pkt.h>
Public Member Functions
PktHandler ()
PktHandler (int ifd, int ofd)
~PktHandler ()
int rx (Pkt **p)
int tx (Pkt *p)
Protected Member Functions
int rx_exact (Pkt **p, int len)
int tx_exact (char *buf, int len)
Protected Attributes
int ifd
int ofd
Detailed Description
Packet Handler class declaration.
This class enables customization of the packet handling layer by providing the capability to configure the input file descriptor and output file descriptor. The defaults are "stdin" and "stdout".
The only state maintained in this class is the 'last_error' variable thus an instance of this class can be reused easily.
Definition at line 147 of file epapi_pkt.h.
Constructor & Destructor Documentation
PktHandler::PktHandler ()
Constructor
Standard input and output descriptors ie. stdin and stdout
Definition at line 119 of file epapi_pkt.cc.
References ifd, epapiBase::last_error, and ofd.
PktHandler::PktHandler (int ifd, int ofd)
Constructor
Parameters:
ifd input file descriptor
ofd output file descriptor
Definition at line 125 of file epapi_pkt.cc.
References ifd, epapiBase::last_error, and ofd.
PktHandler::~PktHandler ()
Definition at line 131 of file epapi_pkt.cc.
Member Function Documentation
int PktHandler::rx (Pkt ** p)
Receive packet
Parameters:
p pointer to packet pointer
Returns:
0 SUCCESS
1 FAILURE
Waits for a complete packet
Returns:
0 SUCCESS
1 FAILURE
Definition at line 168 of file epapi_pkt.cc.
References DBGLOG, EEPAPI_ERRNO, epapiBase::last_error, and rx_exact().
Referenced by MsgHandler::rx().
int PktHandler::rx_exact (Pkt ** p, int len) [protected]
Receive (blocking) a packet
Parameters:
p packet pointer
len packet length
Returns:
>0 LEN read
<=0 ERROR, check errno
Waits for 'len' bytes from the input pipe
Returns:
>=0 len retrieved
<0 ERROR eg. EPIPE
0 ERROR / EOF
Definition at line 144 of file epapi_pkt.cc.
References ifd.
Referenced by rx().
int PktHandler::tx (Pkt * p)
Transmit packet
Parameters:
p pointer to packet
Returns:
0 SUCCESS
1 FAILURE
Transmits a packet
Returns:
0 SUCCESS
1 FAILURE
Definition at line 210 of file epapi_pkt.cc.
References DBGLOG, EEPAPI_ERRNO, EEPAPI_MALLOC, EEPAPI_NULL, Pkt::getTxBuf(), epapiBase::last_error, and tx_exact().
Referenced by MsgHandler::send().
int PktHandler::tx_exact (char * buf, int len) [protected]
Transmits (blocking) a packet
Parameters:
buf packet buffer
len packet length
Returns:
>0 LEN written
<=0 ERROR, check errno
Definition at line 261 of file epapi_pkt.cc.
References ofd.
Referenced by tx().
Field Documentation
int PktHandler::ifd [protected]
Definition at line 150 of file epapi_pkt.h.
Referenced by PktHandler(), and rx_exact().
int PktHandler::ofd [protected]
Definition at line 151 of file epapi_pkt.h.
Referenced by PktHandler(), and tx_exact().
The documentation for this class was generated from the following files:
/home/jldupont/workspace/epapi/trunk/project/lib/include/epapi_pkt.h
/home/jldupont/workspace/epapi/trunk/project/lib/src/epapi_pkt.cc