"""
scons build file

	p

@author: Jean-Lou Dupont
"""

Import('env')

d = env.Dictionary()

#no difference at this point
if d.get('_DEBUG', False):
	#DEBUG
	libs=['ei',]
	pr = env.Program('decho', Glob("src/*.cc"), LIBS=libs )	
else:
	#RELEASE
	libs=['ei',]
	pr = env.Program('echo', Glob("src/*.cc"), LIBS=libs )
	
Default(pr)
